### ISSUE TITLE
Describing Edge in terms of segments

### ISSUE THREAD

**Issue by debeshmandal** [shanilpanara/origamiUROP#11]
## Summary
It has been pointed out that a strand of DNA should really be thought of as a quantized length with an integer number of segments with equal length.

We need to implement this segmentation into our current implementation of an `Edge`

This issue has no plan for how to do this, and for now shall be used for brainstorming

**Comment by shanilpanara** [comment]
## Thoughts
Right, so firstly all of the below would only apply in the situation that the `kind` of edge is a scaffold/staple `(values: 1 or 2)`. If so, we initialise the creation of a strand and it's nucleotides when we initialise this type of edge.

Then using discretised system, as you mentioned in the call yesterday, using integers only, where there is a base pair per index/position. Separately we can define the real life size conversion between each index position, i.e. distance between [3,0,0] and [4,0,0] is [1,0,0] or 6nm for example, which represents one base. This would mean `vertex_1` and `vertex_2` would need to an integer distance apart, and also we would need check they meet a minimum size requirement (of 10 bases, as required before folding can occur).

In my mind, all edge "segments" represent the **centerline** around which the DNA will form, such that the `dir` (the vector parallel to the direction of stacking - a3 vector) is the most important. We then implement the creation of a strand as https://github.com/rgatkinson/oxdna/blob/master/UTILS/generators.py implemented here.

Maybe I'm way off track and don't understand the problem at hand. Let me know your thoughts @debeshmandal :)

**Comment by debeshmandal** [comment]
Overall, you're on the right track, but here are some important points:

## Categorising things

In Python (or Javascript which is probably the most popular programming language in the world at the moment), we don't need to use integers to categorise things, because we can use dictionaries - this makes the code more readable, and also the is little-to-no change in performance due to the architecture of Python.

e.g. instead of categorising the edge_type as: `1` or `2` (i.e. using integers), we can use: `'scaffold'` or `'staple'`. Here would be to implementations that would work (almost) equally well, but the second uses strings and is more readable:

```python
def function_scaffold():
    something
    return

def function_staple():
    something_else
    return

function_list = [function_scaffold, function_staple]
function_dict = {
    'scaffold' : function_scaffold,
    'staple' : function_staple
}

# also remember to avoid using the word type 
# since it is an existing function in Python
edge_1 = Edge(kind=0)

edge_2 = Edge(kind='scaffold')

function_list[edge_1.kind]() # does something
function_dict[edge_2.kind]() # does something as well and the syntax is the same
```
In short, use strings for characterising quantities that you would describe using words because it improves readability and doesn't offer a great deal of performance to us in Python

## Using a square lattice

I'm not too sure on how this will work in practice. When you say that the distance between two points must also be an integer, I don't know if this is correct or not (I'm leaning towards it not being correct but I could be wrong).

Using a square lattice is the same as using an integer-only cartesian co-ordinate system. However, this would very rarely yield integer distances between co-ordinate pairs. I think the best thing to do is to create polygons as before and try to populate them with DNA, and then during visualisation we will notice any issues and can fix them appropriately.

## Creating a DNA strand

What you have said so far is correct, but there is one thing you have forgotten, that will be important for us to implement in our edit of the oxDNA code.

This is difficult to describe without diagrams, but in short:
  - we will create a DNA strand that 'surrounds' the vector described using `dir`
  - visualising this along the axis, we would see a circle
  - however, there is one more parameter that we can control, which is the 'angle' around the circle that the first nucleotide is based. To imagine this, imagine working in polar co-ordinates (r, theta), the value for r is fixed (can be found in the `generators.py` file) but the value for theta is free for us to control. We will need to be able to control this appropriately (in 3D), and there may already be a parameter for this called `perp` or something like that. The best way to understand will be to create visualisations.
  - to visualise we can use Ovito - this also has a Python API - don't worry about using the Python API for this yet, but we will in the future to help with visualisation

**Comment by shanilpanara** [comment]
Amazing! This is really insightful and well explained, things are slowly starting to make more and more sense.

Thanks, I look forward to having a productive day tomorrow trying to expand on what we have 😄

**Comment by shanilpanara** [comment]
@debeshmandal After writing the other issue (#18) I had some thoughts with regards to representing a **square lattice**. 

To simplify things, when we create the scaffold, it could be an idea to use units of `turns` and or instead `half_turns` of DNA, since this is the smallest unit we need to be thinking about when generating the scaffold. After this we can translate these turns into a number of bases and calculate the distance between them and hence locations. i.e. **1.5 turns = 16 bases**

**Comment by debeshmandal** [comment]
You need to read up on reduced units and the oxDNA units system before we continue with this since we are not working in terms of nm but oxDNA sigma instead.

**Comment by debeshmandal** [comment]
This will tie in with #36 because the number of segments will determine the preferred vector/angle at each end of an Edge
