### ISSUE TITLE
Populate an Edge with a DNA single/double Helix

### ISSUE THREAD

**Issue by debeshmandal** [shanilpanara/origamiUROP#5]
## Summary

Within the code we have something that represents an edge, most probably a class called `Edge`.

We now need to use this edge to act as a template for a strand of DNA that can wrap around it.

There is a repository found here: https://github.com/lorenzo-rovigatti/tacoxDNA - this contains conversions to/from the oxDNA file format.

Also this file: https://github.com/rgatkinson/oxdna/blob/master/UTILS/generators.py shows how to generate an oxDNA DNA strand with the geometry of the single/double helix

We basically need a function within/subclass of `Edge` that contains the important information needed to generate the oxDNA file + further, this must be created for each nucleotide (3 columns each, 15 columns in total)

- [ ] position (**centre-of-mass**/base/backbone [not sure which])
- [ ] a_1 vector
- [ ] a_3 vector
- [ ] linear velocity (can be initialised to 0.0 to start)
- [ ] angular velocity (can be initialised to 0.0 to start)

Further, we need to create a topology file that describes the bonding. For this we need the following information (1 column each)

- [ ] strand number
- [ ] base (e.g. 'A', 'T', 'C', 'G')
- [ ] nucleotide before (3' direction)
- [ ] nucleotide after (5' direction)

**Comment by debeshmandal** [comment]
@shanilpanara Try and get this issue done before our next meeting - I think we might not end up using the `Edge` class in the same way that I intended but we can move the code to a different class if necessary.

**Comment by shanilpanara** [comment]
#### Mini update
![image](https://user-images.githubusercontent.com/67636677/87932186-01538a00-ca83-11ea-9649-0d6f272a93e5.png)
 - managed to copy/simplify/tweak the oxdna code to generate a single helicies for a given length of nucleotides
- also copied / tweaked the option to generate a double helicies [i.e. single strand in reverse] too (we probably wont need it, atleast in this current form, but was just for visualisation in ovito)
#### Edge Length -> Strand of "x" number of nucleotides
Still need to read up on reduced units (didn't have a meeting with Stefano this morning) and hoping to briefly discuss that tomorrow with you. But for now I think I'm going to arbitrarily program in a conversion between the two which we can change later.

**Comment by debeshmandal** [comment]
@shanilpanara This is great - I will take a look at what you have done, but if you can successfully render the DNA then that is essentially all we needed to do here - I'll close this issue once I've had a quick look

**Comment by shanilpanara** [comment]
@debeshmandal just about to have lunch, will make some changes after and then push! I'll let you know when I've done that

**Comment by debeshmandal** [comment]
Closing because this seems done - we can reopen in future if there are any problems
